package net.lemnik.eodsql;

import java.sql.Connection;

/**
 * Minimal stub for QueryTool to satisfy static checks in the editor.
 * The real implementation is provided by the eodsql library at runtime.
 */
public class QueryTool {
    public static <T> T getQuery(Connection connection, Class<T> cls) {
        return null; // stub - real implementation generated by eodsql at runtime
    }
}
